### ISSUE TITLE
Refactor PrometheusRulesProvider

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#183]
## Issue
The `PrometheusRulesProvider` at present annotates alert rules using Juju topology labels. This does not seem to concur with its intended use case of supporting ingestion of alert rules that are not associated with any particular scrape job, or application of model. 

The may also require a refactor of the `AlertRules` object. These refactorings may also need to take into consideration issue #171.

**Comment by Abuelodelanada** [comment]
As far as I understand [`topology` is an Optional parameter in `__init__` in  `AlertRules`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L776)


```python
def __init__(self, topology: Optional[JujuTopology] = None):
```

When [`AlertRules` is instantiated in `PrometheusRulesProvider`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1740), no `topology` is used:

```python
        alert_rules = AlertRules()
``` 

With this, [no topology is injected in alert rules labels](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L830):

```python
                    if self.topology:
                        alert_rule["labels"].update(self.topology.as_promql_label_dict())
                        # insert juju topology filters into a prometheus alert rule
                        alert_rule["expr"] = self.topology.render(alert_rule["expr"])
```

Since no topology is used in `PrometheusRulesProvider`, I think [we can remove line 1707](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1707):

```python
self.topology = ProviderTopology.from_charm(charm)
```

Is this correct @balbirthomas o am I missing something??

**Comment by balbirthomas** [comment]
@Abuelodelanada Prima Facie that makes sense. However isn't there a plan to deprecate and remove `PrometheusRulesProvider` ? If so this would be a moot point. Also @sed-i may be more familiar with this object.
