### ISSUE TITLE
Remote write provider must handle scaling of parent charm

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#271]
### Bug Description

Suppose a charm uses the Prometheus remote write provider library. Now suppose this charm has a peer relation and can be scaled to have more than one unit. This scaling increases the number of remote write endpoints that must be written to. Likewise scaling down reduces the number of remote write endpoints that must be written to. However the current remote write provider only has event bindings for [relation-created](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L954) and [relation-joined](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L958). Are these two event bindings sufficient ? Do we need further bindings for events such as relation departed or even the parent charms peer relation event ?

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by sed-i** [comment]
Related to #173.

**Comment by balbirthomas** [comment]
> Related to #173.

Though #173 is about the Prometheus charm. But this is about the charm using the remote write library. One test (if possible unit) that would be useful here is
- Add a peer unit to the (fake) parent charm of the remote write provider library
- Check it sets an additional endpoint for the remote write consumer charm.
This test captures the use case I was trying to raise in this ticket.

**Comment by sed-i** [comment]
Looks like the provider stores the endpoint address in unit data, 

https://github.com/canonical/prometheus-k8s-operator/blob/a3d80a0b94bf5cf0a340efaa0fa463f96fef858f/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L1004-L1008

so I think:
- rescale is covered by juju lifecycle
- we should still explicitly handle upgrade, because address may change
- add a listener to the constructor so we could pass into it `self.ingress.on.ingress_changed` from outside.

WDYT @balbirthomas @rbarry82?
