### ISSUE TITLE
External hostname is not updated if an ingress is added *after* relating a charm to Prometheus

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#368]
### Bug Description

See title. If you first relate to Prometheus and then to Traefik, it all works as expected. The other way around, no cigar.

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

### Additional context

[We could have used the ingress established/revoked events, but these are unfortunately fired prematurely](https://github.com/canonical/traefik-k8s-operator/issues/78)

**Comment by sed-i** [comment]
## Reproduction
After relating a charm to traefik, its metrics endpoint is not updated and prometheus reports `health: down` because it is no longer reachable via the local ip.

1. am, prom, trfk deployed and all in active/idle.
1. juju relate am:self-metrics-endpoint prom
   - curl 10.1.13.182:9090/api/v1/targets | jq '.data.activeTargets'
     - "scrapeUrl": "http://10.1.13.180:9093/metrics",
     - "globalUrl": "http://10.1.13.180:9093/metrics",
     - "health": "up",
1. juju relate am trfk
   - curl 10.1.13.182:9090/api/v1/targets | jq '.data.activeTargets'
     - "scrapeUrl": "http://10.1.13.180:9093/metrics",
     - "globalUrl": "http://10.1.13.180:9093/metrics",
     - "health": "down",
1. juju run-action trfk/0 show-proxied-endpoints --wait
     - proxied-endpoints: '{"am": {"url": "http://10.128.0.3:80/wlcm2-am"}}'

- update-status didn't help because the lib doesn't automatically observe it for sidecars, and alertmanager [didn't pass custom refresh events](https://github.com/canonical/alertmanager-k8s-operator/blob/c999a45278c1c5064d6b8ca41eea7a54838b3fe8/src/charm.py#L139).

## Proposal 1
Users of MetricsEndpointProvider must be instructed to always set custom refresh events

```
self.metrics = MetricsEndpointProvider(
    # ...
    refresh_event=[  # needed for ingress
        self.ingress.on.ready_for_unit,
        self.ingress.on.revoked_for_unit,
        self.on.update_status,
    ]
```

## Proposal 2
MetricsEndpointProvider should [always observe update-status by default](https://github.com/canonical/prometheus-k8s-operator/blob/0e410410da9dd6f64fbd63c2b35383ecc7d2b9cb/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1539).

## Proposal 3
MetricsEndpointProvider should update relation data every re-init.
I.e. the contructor MetricsEndpointProvider should call [`self._set_scrape_job_spec`](https://github.com/canonical/prometheus-k8s-operator/blob/0e410410da9dd6f64fbd63c2b35383ecc7d2b9cb/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1577) every instantiation, instead of registring it as an observer.

Ideas? @dstathis @Abuelodelanada @rbarry82

**Comment by rbarry82** [comment]
I think proposal #3 is preferable by far. It's idempotent, users don't have to do anything at all, it doesn't depend on `update-status-interval` or calling other events, and it can easily be removed from the library constructor when [`stripPrefix` middleware lands in traefik](https://github.com/canonical/traefik-k8s-operator/issues/45), which makes this problem more or less disappear entirely (at least from an in-model/cluster perspective, as well as any external targets which have routable endpoints and don't need a path specified by any reverse proxy).

**Comment by sed-i** [comment]
Tested manually and the combination of:
- https://github.com/canonical/prometheus-k8s-operator/pull/384 and
- https://github.com/canonical/alertmanager-k8s-operator/pull/103 (with the modified prom lib)

solves the issue.

With which charm did you experience this @simskij ? You may need to update charm code:
- fetch-lib for prometheus_scrape
- pass `external_url` to MetricsEndpointProvider
- use correct port number for the job `port = urlparse(self._external_url).port or 80`

**Comment by sed-i** [comment]
> I saw it with the loki datasource in grafana after deploying it as a bundle.

If it's a loki datasource issue then perhaps it's not related to prometheus_scrape?

Maybe we need to manually call [`update_source`](https://github.com/canonical/grafana-k8s-operator/blob/376005c67a60e918353319de0f654248a9ef7e2c/lib/charms/grafana_k8s/v0/grafana_source.py#L412) in loki?
BTW, `update_source` seems very different from [`refresh_event`](https://github.com/canonical/grafana-k8s-operator/blob/376005c67a60e918353319de0f654248a9ef7e2c/lib/charms/grafana_k8s/v0/grafana_source.py#L410).
@dstathis @rbarry82

**Comment by rbarry82** [comment]
> Maybe we need to manually call [`update_source`](https://github.com/canonical/grafana-k8s-operator/blob/376005c67a60e918353319de0f654248a9ef7e2c/lib/charms/grafana_k8s/v0/grafana_source.py#L412) in loki? BTW, `update_source` seems very different from [`refresh_event`](https://github.com/canonical/grafana-k8s-operator/blob/376005c67a60e918353319de0f654248a9ef7e2c/lib/charms/grafana_k8s/v0/grafana_source.py#L410). @dstathis @rbarry82

`update_source` is just a superset of `_set_unit_details` which also allows passing additional fields, and was added explicitly for consumers to say "I have an ingress now, so update out-of-band in case `GrafanaSourceProvider._source_url` from the constructor is out of date".

Since Loki [already uses the property in the constructor](https://github.com/canonical/loki-k8s-operator/blob/main/src/charm.py#L96), `update_source` would be called when an ingress is added, yes, which allows setting/updating the Grafana relation data immediately after `ingress_ready` rather than waiting for some other event to re-trigger the constructor. We could do the same thing in `grafana_source` as is done here, but it would make sense from Loki's codebase to add it just after `update_endpoint(...)`, since the semantics are the same. The Prometheus libraries have just obsessively avoiding having any public API at all which could be used for this purpose.

**Comment by simskij** [comment]
My bad, I saw it in Prometheus too, but it seems to have been resolved now.
