### ISSUE TITLE
Move constants to a separate file?

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#430]
### Enhancement Proposal

In itests, if we want to reuse e.g. `PROMETHEUS_CONFIG`, we could import it directly

```python
from src.charm import PROMETHEUS_CONFIG
```

But without including `requirements.txt` in the deps of the tox integration env, this won't work:
```
tests/integration/test_upgrade_charm.py:7: in <module>
    from src.charm import PROMETHEUS_CONFIG
src/charm.py:15: in <module>
    from charms.alertmanager_k8s.v0.alertmanager_dispatch import AlertmanagerConsumer
lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py:32: in <module>
    import ops
E   ModuleNotFoundError: No module named 'ops'
```
because `charm.py` has a ton of deps which are not installed for itests.

Having constants in a separate, dependencies-free file could be beneficial.
(In our case, `*.py` is probably more practical than a `conf/ini/toml` file.)

**Comment by rbarry82** [comment]
Tests should not be dependent on runtime code for their definition, much as the earlier conversation about using factories from library code inside unit tests. It creates a coupling between the _expected_ behavior (the tests) and the _actual behavior_ (the code which is being tested), and it's a dangerous antipattern. A separate QA team, even an internal one, would never pursue this strategy, and that's telling.

The "dependency injection" (mocking/magicmocking in Python, generally) case where unit tests must exercise code which has side effects (network/disk/database access, authorization to an external service, etc) is typically the only time this is used, and that would be more of "construct an object which has the same methods+signatures but doesn't actually exercise the destructive parts"

Is there a meaningful use case for introducing this rather than defining them as test-level constants (in conftest.py or other)? Particularly for what is, in actuality, two short strings?

**Comment by sed-i** [comment]
> Tests should not be dependent on runtime code for their definition

True, in general. However, we already have a pretty big exception: the vast majority of our tests use a "runtime" `metadata.yaml` instead of hardcoding it again.

Hard coding some things in tests is useful. Not sure about file paths (such as `PROMETHEUS_CONFIG`).

**Comment by rbarry82** [comment]
We do use a "runtime" `metadata.yaml` as scaffolding. I think some is a little unavoidable inside the charming ecosystem.

Even if there were a method which returned the value of this (`src/config.get_config_path()` or something) which was mocked out/overridden in tests, it would be less concerning. Importing runtime code directly to _use it_ rather than using it to exercise some specific workflow is a slippery slope which could give us unreliable test results. Once it's done in one place, it becomes a pattern that new/unfamiliar authors see and may use, and then some future PR doesn't have an additional "`from ... import ...` stanza at the top, because it's already there.

It's annoying, duplicated boilerplate to avoid it. But picking `prometheus_scrape.DEFAULT_JOBS|ALLOWED_KEYS` as other annoying, duplicated boilerplate constants, those also aren't imported into unit tests at present, and we probably wouldn't want them to be. In a perfect world, where every reviewer has 100% attention to every PR, it would nominally be ok, because a typo or mistake in some constant would be noticed, and not just scrolled past as "probably ok, the tests are green". 

I'm not that perfect, and I imagine a future issue where we create an accidental bug/regression when a user sends some relation data which is more complex or differs from the stanzas we test in such a way where it slips through in a way that's invalid. Spending the extra time and to keep "constants" in sync across both areas is a worthwhile tradeoff to me, at least.

**Comment by sed-i** [comment]
Agreed, except there won't be a `from src.charm import whatever`, but rather a carefully scoped `from src.consts import whatever`.
I think that changes made to `consts.py` would be obvious enough in a PR.

**Comment by rbarry82** [comment]
"Thou shalt not depend on the code under test" is as close to a commandment as it gets no matter how carefully scoped. 

Lots of the reason that writing tests is onerous is that there's a ton of duplication. Python can't really enforce whether or something is constant or not anyway, but it's not important. This is like double-entry accounting. It's a little more work for a lot more safety, and if we're "carefully scoping" what constants would make it into `consts.py`, then it's worth the extra bit of effort to just carefully scope it into `tests/integration/consts.py` instead. We want an immediate, clear warning if the test data doesn't match _what we expect_. Not how the code expects to behave, or whether it just kinda happens to pass the tests (you can only test the bugs you know about), but about how _we expect_ it to behave, and we can't make those kinds of assertions if changing runtime code silently adjusts the expectation.

**Comment by sed-i** [comment]
I think we are still in agreement and in no contradiction to the proposal.
This enhancement proposal is not important enough to continue though.
Closing.
