### ISSUE TITLE
Wrong log level when the alert rules validation fails

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-k8s-operator#456]
### Enhancement Proposal

Right now, the `CosTool`'s method `validate_alert_rules` that is present in:

- [`prometheus_scrape`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L2381)
- [`prometheus_remote_write`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L1047)
- [`grafana_dashboard`](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1927)

logs in a `DEBUG` level if the validation of alter rules fails:

```python
    def validate_alert_rules(self, rules: dict) -> Tuple[bool, str]:
        """Will validate correctness of alert rules, returning a boolean and any errors."""
        if not self.path:
            logger.debug("`cos-tool` unavailable. Not validating alert correctness.")
            return True, ""

        with tempfile.TemporaryDirectory() as tmpdir:
            rule_path = Path(tmpdir + "/validate_rule.yaml")
            rule_path.write_text(yaml.dump(rules))

            args = [str(self.path), "validate", str(rule_path)]
            # noinspection PyBroadException
            try:
                self._exec(args)
                return True, ""
            except subprocess.CalledProcessError as e:
                logger.debug("Validating the rules failed: %s", e.output)
                return False, ", ".join(
                    [
                        line
                        for line in e.output.decode("utf8").splitlines()
                        if "error validating" in line
                    ]
                )
```

For instance, alert rules labels [must adhere to the following regex `[a-zA-Z_]([a-zA-Z0-9_])*`](https://github.com/prometheus/client_java/issues/28).

So a label named `app-group` is invalid while `app_group` is valid:

```shell
$ ./cos-tool-amd64 validate src/prometheus_alert_rules/wrong.rule
error validating: group "cos_23790144_zinc2_zinc_missing_alerts", rule 1, "ZincTargetMissing": invalid label name: app-group
```

This is troublesome, as trivial errors in alert rules files can go undetected since debug level produces a lot of log lines.

In the following deployment

- `zinc` app has a wrong alert rule
```yaml
    for: 0m
    labels:
      app-group: cloud
      juju_application: zinc2
```

- `zincs` app has a right alert rule
```yaml
    for: 0m
    labels:
      app_group: cloud
      juju_application: zinc2
```

But in the status you see no error nor warning

```shell
$ juju status --color --relations           
Model  Controller           Cloud/Region        Version  SLA          Timestamp
cos    charm-dev-batteries  microk8s/localhost  3.0.2    unsupported  20:38:26-03:00

App         Version  Status  Scale  Charm           Channel  Rev  Address         Exposed  Message
prometheus  2.42.0   active      1  prometheus-k8s  edge     110  10.152.183.251  no       
zinc        0.3.6    active      1  zinc-k8s                   0  10.152.183.206  no       
zinc2       0.3.6    active      1  zinc-k8s                   1  10.152.183.86   no       

Unit           Workload  Agent  Address      Ports  Message
prometheus/0*  active    idle   10.1.36.124         
zinc2/0*       active    idle   10.1.36.110         
zinc/0*        active    idle   10.1.36.91          

Relation provider            Requirer                     Interface          Type     Message
prometheus:prometheus-peers  prometheus:prometheus-peers  prometheus_peers   peer     
zinc2:metrics-endpoint       prometheus:metrics-endpoint  prometheus_scrape  regular  
zinc:metrics-endpoint        prometheus:metrics-endpoint  prometheus_scrape  regular  
```

The only thing you can find is in the juju debug-log

```shell
$ jdl --replay | grep "Validating the"                                                                                       
unit-prometheus-0: 19:56:09.494 DEBUG unit.prometheus/0.juju-log metrics-endpoint:14: Validating the rules failed: b'error validating: group "cos_23790144_zinc_zinc_missing_alerts", rule 1, "ZincTargetMissing": invalid label name: app-group\n'
```

## Suggestions

- Increase the log level from `debug` to `warning`
- Shouldn't the application that sends an incorrect alert rule file be in `warning` status?

**Comment by rbarry82** [comment]
To be clear, `grafana_dashboard` doesn't exercise this at all. It's just there because it's in `CosTool` for label injection.

But Prometheus [puts it back in relation data](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1199), and [so does `remote_write`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L993). 

[Both](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1598) will [emit](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py#L660) an event to the providing charm with that error.

The reason for this is because `cos-tool` is only present in the consumer/requirer, but in large deployments, emitting every failure from `loki-0` or `prometheus-0` would not be at all obvious or give the author any indication of which charm actually _contains_ the problem rule.

In both cases, if such an error is flagged and sent back (where our design model/hope is that charm authors consuming the libraries will actually listen to it and choose what to do), the alert rule is not actually propagated through to Prom/Loki, so they stay in a working state.

This model is clearly not perfect, and we could issue a `warning` level log from the charm which provided the rule to ensure that authors see it even if they choose not to observe the event (or didn't notice it), but there is, at least, a clear pattern for this which is re-used in almost all of our charms which is more visible than debug logging.

**Comment by simskij** [comment]
Closing this given @rbarry82's feedback.
